[package]
name = "dec18"
version = "0.1.0"
authors = ["Ted C. Howard <ted@tedchoward.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
